package Apec.Settings;

public enum SettingID {

    AUTO_ENABLE,
    SHOW_WARNING,
    SHOW_POTIONS_EFFECTS,
    SHOW_DEBUG_MESSAGES,
    OVERWRITE_GUI,
    NPC_GUI,
    INVENTORY_TRAFFIC,
    HIDE_IN_F3,
    SHOW_SKILL_XP,
    BORDER_TYPE,
    COMPACT_POTION,
    ITEM_HIGHLIGHT_TEXT,
    HP_BAR,
    MP_BAR,
    XP_BAR,
    HIDE_NIGHT_VISION,
    ALWAYS_SHOW_SKILL,
    SHOW_CACHED_PURSE_IN_DUNGEONS,
    SHOW_AIR_BAR,
    SNAP_IN_EDITING,
    INFO_BOX_ANIMATION,
    SHOW_ABILITY_TEXT,
    SHOW_ABSORPTION_BAR

}
